services:

  proxy:
    image: nginx:1.29.5-alpine
    container_name: renovar_proxy
    volumes:
      - type: bind
        source: ./nginx.conf 
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - api
      - minio

  api:
    build: .
    container_name: renovar_api
    restart: unless-stopped ## lembrar que se desligar a ec2, tem que ligar o container dnv 
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: renovar_minio
    restart: unless-stopped
    command: server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    volumes:
      - minio_data:/data

volumes:
  minio_data:
