services:
  - type: web
    name: renovar-api
    runtime: docker
    plan: free
    region: oregon # ou 'singapore', 'frankfurt', 'ohio'
    branch: main
    
    envVars:
      # --- Banco de Dados (Render -> Java) ---
      - key: DB_USERNAME
        fromDatabase:
          name: renovar-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: renovar-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: renovar-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: renovar-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: renovar-db
          property: database

      # --- JWT (Segurança) ---
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_SEC
        value: "7200"

databases:
  - name: renovar-db
    plan: free
    region: oregon # Mesma região do serviço web
    user: renovar_user